services:
  mongodb:
    image: "mongo:7-jammy"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    restart: unless-stopped
  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    restart: unless-stopped

  rekoni:
    image: hardcoreeng/rekoni-service:v0.6.377
    environment:
      - SECRET=${HULY_SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rekoni.entrypoints=websecure"
      - "traefik.http.services.rekoni.loadbalancer.server.port=4004"
      - "traefik.http.routers.rekoni.rule=Host(`huly.sinesys.app`) && PathPrefix(`/rekoni`)"
      - "traefik.http.routers.rekoni.middlewares=rekoni-stripprefix"
      - "traefik.http.middlewares.rekoni-stripprefix.stripprefix.prefixes=/rekoni"
      - "traefik.http.routers.rekoni.tls=true"
      - "traefik.http.routers.rekoni.tls.certresolver=myresolver"

  transactor:
    image: hardcoreeng/transactor:v0.6.377
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${HULY_SECRET}
      - SERVER_CURSOR_MAXTIMEMS=30000
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://localhost:8087
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transactor.entrypoints=transactor"
      - "traefik.http.routers.transactor.rule=Host(`huly.sinesys.app`)"
      - "traefik.http.services.transactor.loadbalancer.server.port=3333"
      - "traefik.http.routers.transactor.tls=true"
      - "traefik.http.routers.transactor.tls.certresolver=myresolver"

  collaborator:
    image: hardcoreeng/collaborator:v0.6.377
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaborator.entrypoints=collaborator"
      - "traefik.http.services.collaborator.loadbalancer.server.port=3078"
      - "traefik.http.routers.collaborator.rule=Host(`huly.sinesys.app`)"
      - "traefik.http.routers.collaborator.tls=true"
      - "traefik.http.routers.collaborator.tls.certresolver=myresolver"

  account:
    image: hardcoreeng/account:v0.6.377
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;wss://huly.sinesys.app:3333
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://front:8080
      - STATS_URL=http://stats:4900
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.entrypoints=websecure"
      - "traefik.http.services.account.loadbalancer.server.port=3000"
      - "traefik.http.routers.account.rule=Host(`huly.sinesys.app`) && PathPrefix(`/accounts`)"
      - "traefik.http.routers.account.middlewares=account-stripprefix"
      - "traefik.http.middlewares.account-stripprefix.stripprefix.prefixes=/accounts"
      - "traefik.http.routers.account.tls=true"
      - "traefik.http.routers.account.tls.certresolver=myresolver"

  workspace:
    image: hardcoreeng/workspace:v0.6.377
    environment:
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;wss://huly.sineys.app:3333
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
    restart: unless-stopped

  front:
    image: hardcoreeng/front:v0.6.377
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=https://huly.sinesys.app/accounts
      - REKONI_URL=https://huly.sinesys.app/rekoni
      - CALENDAR_URL=https://huly.sinesys.app:8095
      - GMAIL_URL=https://huly.sinesys.app:8088
      - TELEGRAM_URL=https://huly.sinesys.app:8086
      - STATS_URL=https://huly.sinesys.app/stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=wss://huly.sinesys.app:3078
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=Huly Self Host
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
      - DESKTOP_UPDATES_CHANNEL=selfhost
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front.rule=Host(`huly.sinesys.app`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=myresolver"

  fulltext:
    image: hardcoreeng/fulltext:v0.6.377
    environment:
      - SERVER_SECRET=${HULY_SECRET}
      - DB_URL=mongodb://mongodb:27017
      - FULLTEXT_DB_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
    restart: unless-stopped

  stats:
    image: hardcoreeng/stats:v0.6.377
    environment:
      - PORT=4900
      - SERVER_SECRET=${HULY_SECRET}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.entrypoints=websecure"
      - "traefik.http.services.stats.loadbalancer.server.port=4900"
      - "traefik.http.routers.stats.rule=Host(`huly.sinesys.app`) && PathPrefix(`/stats`)"
      - "traefik.http.routers.stats.middlewares=stats-stripprefix"
      - "traefik.http.middlewares.stats-stripprefix.stripprefix.prefixes=/stats"
      - "traefik.http.routers.stats.tls=true"
      - "traefik.http.routers.stats.tls.certresolver=myresolver"

volumes:
  db:
  elastic:
  files:
